apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: tanzu-helm-resources
spec:
  interval: 10m0s
  timeout: 60s
  url: https://charts.bitnami.com/bitnami